baseurl = "http://ryouens.com/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Lori Ortiz"
title = "Rachel Youens"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Rachel Youens is a Brooklyn-based artist."
copyright = "© 2019 Rachel Youens"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = false
progressively = true
lang = "en"
share = true
disablefancyfonts = true
# Share to googleplus, twitter, fb, linkedin by default
# disable by setting share_on_<social network> = false
# example: share_on_googleplus = false
latestpostcount = 5
github = ""
email = "rachelyouens@verizon.net"
linkedin = ""
twitter = ""
facebook = ""
social_banner = "img/banner.jpg"
usesmallsummarycard = true
posts_navigation = true
small_banner_logo = true

[params.colors]
identifier = "#527fc1"
identifier_dark = "#1a3152"
trivial = "#a0a0a0"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"
